### ISSUE TITLE
"koch" error on Windows

### ISSUE THREAD

**Issue by matkuki** [nim-lang/csources#10]
When following the instructions for building Nim on Windows, the last line:
> **koch boot -d:release**

throws an error during processing:

> ...\nim-devel\lib\packages\docutils\rstgen.nim(606, 6) Error: type mismatch: got (seq[string], proc (T, T): int)
> but expected one of:
> tables.sort(t: OrderedTableRef[A, B], cmp: proc (tuple[key: A, val: B], tuple[key: A, val: B]): int{.closure.})
> tables.sort(t: CountTableRef[A])
> tables.sort(t: var CountTable[A])
> tables.sort(t: var OrderedTable[A, B], cmp: proc (tuple[key: A, val: B], tuple[key: A, val: B]): int{.closure.})
> algorithm.sort(a: var openarray[T], cmp: proc (T, T): int{.closure.}, order: SortOrder)
> FAILURE

A couple of weeks back it was working though.
If more information is needed, notify me.

**Comment by dom96** [comment]
These bugs belong in [Araq/Nim](http://github.com/Araq/nim)
