### ISSUE TITLE
Tag for v0.10.2

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/csources#11]
Please run `git tag v0.10.2 96a5b7fe23eb1964f2e68e455f14246b390b9507`.

**Comment by dom96** [comment]
As i've said in https://github.com/nim-lang/csources/issues/7#issuecomment-68953444 we won't be tagging C sources.

**Comment by reactormonk** [comment]
Yes, the repo will be big. But the tags aren't for git itself, the are for github to create versions in https://github.com/nim-lang/csources/releases

**Comment by dom96** [comment]
The release C sources are available on the Nim website.

**Comment by dom96** [comment]
This repos purpose is to provide devel C sources.
