### ISSUE TITLE
why no releases since v19.0.0?

### ISSUE THREAD

**Issue by jackmac92** [nim-lang/csources#25]
It breaks aasdf-nim https://github.com/rfrancis/asdf-nim/issues/5

**Comment by Araq** [comment]
We thought it's not necessary. Will investigate, stay tuned.

**Comment by genotrance** [comment]
Could create multiple tags at the same hash. But I plan on updating asdf to use the xz file instead.

**Comment by ShalokShalom** [comment]
How I am supposed to build via script?

I have Nim setup via a custom build script, which asks for the current version. 

No update here, no update in my system.

**Comment by genotrance** [comment]
There's no need for sub-versions as already documented in the asdf thread. Doesn't this PR fix it for you?

https://github.com/rfrancis/asdf-nim/pull/6

**Comment by ShalokShalom** [comment]
No. I have just explained why. You can easily release a subversion, it costs you the hit of a button and makes the maintainence of the build scripts simple and keeps them concise.

**Comment by Araq** [comment]
We won't update csources anymore. The cources we have now are always good enough to build a version of Nim that can build any Nim version.
