### ISSUE TITLE
What's the difference?

### ISSUE THREAD

**Issue by sheerun** [nim-lang/csources#6]
In README it says:

> Building these will not result in the latest compiler being built, these C sources should be used in conjuction with koch.

Could you explain in README what is the exact difference between `nim` built from this repository and one that is built with koch? Is it not OK to use this repository for building non-development nim?

**Comment by dom96** [comment]
The difference is precisely as stated in the README, i.e. a ``nim`` built from these C sources will be an older snapshot than if bootstrapped from Araq/Nim.
