### ISSUE TITLE
up to date release

### ISSUE THREAD

**Issue by stefantalpalaru** [nim-lang/csources#7]
Please make a release that's able to compile Nim-0.10.2. It would help me make a better Gentoo ebuild and it would probably help all the other distro packagers that want a replicable build.

**Comment by Varriount** [comment]
Are you using the right csources branch? The master branch here can only compile the master branch in the main nim repository. Same for the devel branch.

**Comment by stefantalpalaru** [comment]
I was talking about http://nim-lang.org/download/nim-0.10.2.zip which dom96 said I should use instead of github releases. It comes with its own csources copy and I can use it, but I can't get HTML docs out of it.

**Comment by dom96** [comment]
In that case you should use the master branch of this repo which will always correspond to the latest release of Nim.

**Comment by dom96** [comment]
Perhaps for packaging you could use the C sources in the zip together with a tag of the Nim compiler's repo?

**Comment by stefantalpalaru** [comment]
I went back to using Github for the sources and pinning this repo to the commit hash that I tested. If you delete the commit in the future to save space, the package will break.

On the other hand, there are no old archives on nim-lang.org/download so that's not a valid alternative for the kind of package stability I'm looking for.

**Comment by dom96** [comment]
The archives are still on the server though and they won't be deleted.

**Comment by stefantalpalaru** [comment]
http://nim-lang.org/download/nim-0.9.6.zip is a 404

**Comment by Araq** [comment]
http://nim-lang.org/download/nimrod_0.9.6.zip exists.
