### ISSUE TITLE
Can't get koch to install a Windows build

### ISSUE THREAD

**Issue by bncastle** [nim-lang/csources#8]
Hello,

I am able to build the boostrap nim compiler and successfully get it to boostrap and build nim itself. Where I run into trouble is when I try to install it.

*koch install c:\compiler\nim\bin*

it fails when it tries to do **sh ./install.sh** which is of course a unix command. I'm just wondering if I left something out or if perhaps there is a bug in koch? I poked around a bit to see if there was a corresponding install.bat but could not find one. Any thoughts?

**Comment by dom96** [comment]
I don't think ``koch install`` is for Windows installation. You should just add Nim to your PATH instead.

Please create an issue for this on the [Nim repo](http://github.com/Araq/Nim).
